version: '2'
services:
  configkeyclock-app:
    image: configkeyclock
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://configkeyclock-mysql:3306/configkeyclock?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://configkeyclock-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://configkeyclock-elasticsearch:9200
    ports:
      - 8082:8082
  configkeyclock-mysql:
    extends:
      file: mysql.yml
      service: configkeyclock-mysql
  configkeyclock-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: configkeyclock-elasticsearch
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
